server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 3
      validation-timeout: 60000
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/wallet?autoCommit=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456